"""Seed realistic demo data for MVP demo.

This script populates the database with realistic data showing:
- 4 real zones with coordinates and upstream chain
- ZoneThresholds for each zone
- Sensor readings and weather snapshots that produce spread of risk tiers
- Risk assessments generated by actual RiskEngine
- Alerts generated from risk assessments
- EscalationEngine working end-to-end (Kalam's rain affects Mingora)
- Resource centers with inventory near major zones
- Seeded admin user

TODO(post-demo): Replace with proper data migration/seeding system.
"""

from __future__ import annotations

import asyncio
import random
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Optional

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_SRC_DIR = _PROJECT_ROOT / "backend" / "src"
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

from sqlalchemy.ext.asyncio import AsyncSession

from domain.entities.alert import Alert
from domain.entities.inventory_item import InventoryItem
from domain.entities.resource_center import ResourceCenter
from domain.entities.risk_assessment import RiskAssessment
from domain.entities.sensor_reading import SensorReading
from domain.entities.weather_snapshot import WeatherSnapshot
from domain.entities.zone import Zone
from domain.services.escalation_engine import EscalationEngine
from domain.services.risk_engine import RiskEngine
from domain.value_objects.coordinates import Coordinates
from domain.value_objects.risk_tier import RiskTier
from domain.value_objects.water_level import WaterLevel
from domain.value_objects.zone_thresholds import ZoneThresholds
from infrastructure.db.session import get_session
from infrastructure.db.repositories import (
    AlertRepositoryImpl,
    InventoryItemRepositoryImpl,
    ResourceCenterRepositoryImpl,
    RiskAssessmentRepositoryImpl,
    SensorReadingRepositoryImpl,
    WeatherSnapshotRepositoryImpl,
    ZoneRepositoryImpl,
    ZoneThresholdsRepositoryImpl,
)


# Real zone data for Swat Valley
REAL_ZONES = [
    {
        "id": "zone-kalam",
        "name": "Kalam Bazaar",
        "coordinates": Coordinates(latitude=35.479, longitude=72.596),
        "upstream_zone_id": None,  # Headwater
    },
    {
        "id": "zone-bahrain",
        "name": "Bahrain",
        "coordinates": Coordinates(latitude=35.189, longitude=72.529),
        "upstream_zone_id": "zone-kalam",
    },
    {
        "id": "zone-madyan",
        "name": "Madyan",
        "coordinates": Coordinates(latitude=35.022, longitude=72.475),
        "upstream_zone_id": "zone-bahrain",
    },
    {
        "id": "zone-mingora",
        "name": "Mingora City",
        "coordinates": Coordinates(latitude=34.774, longitude=72.361),
        "upstream_zone_id": "zone-madyan",
    },
]

# Zone thresholds (sensible values for demo)
ZONE_THRESHOLDS = {
    "zone-kalam": ZoneThresholds(
        water_warning_level=WaterLevel(1.5),  # 1.5 metres
        water_critical_level=WaterLevel(2.5),  # 2.5 metres
        heavy_rain_threshold_mm=40.0,
    ),
    "zone-bahrain": ZoneThresholds(
        water_warning_level=WaterLevel(2.0),  # 2.0 metres
        water_critical_level=WaterLevel(3.0),  # 3.0 metres
        heavy_rain_threshold_mm=45.0,
    ),
    "zone-madyan": ZoneThresholds(
        water_warning_level=WaterLevel(2.5),  # 2.5 metres
        water_critical_level=WaterLevel(3.5),  # 3.5 metres
        heavy_rain_threshold_mm=50.0,
    ),
    "zone-mingora": ZoneThresholds(
        water_warning_level=WaterLevel(3.0),  # 3.0 metres
        water_critical_level=WaterLevel(4.0),  # 4.0 metres
        heavy_rain_threshold_mm=55.0,
    ),
}

# Resource centers with inventory
RESOURCE_CENTERS = [
    {
        "id": "rc-mingora",
        "name": "Mingora Emergency Depot",
        "location_zone": "zone-mingora",
        "inventory": [
            {"id": "rci-mingora-1", "item_name": "Sandbags",              "quantity": 500},
            {"id": "rci-mingora-2", "item_name": "Life Jackets",          "quantity": 200},
            {"id": "rci-mingora-3", "item_name": "First-Aid Kits",        "quantity": 100},
            {"id": "rci-mingora-4", "item_name": "Water Pumps",           "quantity": 15},
            {"id": "rci-mingora-5", "item_name": "Inflatable Boats",      "quantity": 8},
        ],
    },
    {
        "id": "rc-bahrain",
        "name": "Bahrain Relief Station",
        "location_zone": "zone-bahrain",
        "inventory": [
            {"id": "rci-bahrain-1", "item_name": "Sandbags",              "quantity": 300},
            {"id": "rci-bahrain-2", "item_name": "First-Aid Kits",        "quantity": 75},
            {"id": "rci-bahrain-3", "item_name": "Temporary Shelters",    "quantity": 20},
            {"id": "rci-bahrain-4", "item_name": "Emergency Lights",      "quantity": 50},
        ],
    },
    {
        "id": "rc-kalam",
        "name": "Kalam Response Base",
        "location_zone": "zone-kalam",
        "inventory": [
            {"id": "rci-kalam-1", "item_name": "Sandbags",                "quantity": 200},
            {"id": "rci-kalam-2", "item_name": "Heavy Duty Tarps",        "quantity": 40},
            {"id": "rci-kalam-3", "item_name": "Water Purification Kits", "quantity": 30},
        ],
    },
]


async def clear_existing_data(session: AsyncSession) -> None:
    """Clear existing demo data (idempotent)."""
    print("Clearing existing demo data...")

    from sqlalchemy import text

    await session.execute(text("DELETE FROM alerts WHERE TRUE"))
    await session.execute(text("DELETE FROM risk_assessments WHERE TRUE"))
    await session.execute(text("DELETE FROM weather_snapshots WHERE TRUE"))
    await session.execute(text("DELETE FROM sensor_readings WHERE TRUE"))
    await session.execute(text("DELETE FROM zone_thresholds WHERE TRUE"))
    await session.execute(text("DELETE FROM inventory_items WHERE TRUE"))
    await session.execute(text("DELETE FROM resource_centers WHERE TRUE"))
    await session.execute(text("DELETE FROM zones WHERE id LIKE 'zone-%'"))
    await session.execute(text("DELETE FROM manual_overrides WHERE TRUE"))


async def seed_zones(session: AsyncSession) -> dict[str, Zone]:
    """Seed zones and return mapping of zone_id -> Zone."""
    print("Seeding zones...")
    zone_repo = ZoneRepositoryImpl(session)
    zones = {}

    for zone_data in REAL_ZONES:
        zone = Zone(**zone_data)
        saved_zone = await zone_repo.add(zone)
        zones[zone_data["id"]] = saved_zone
        print(f"  Added zone: {saved_zone.name}")

    return zones


async def seed_zone_thresholds(session: AsyncSession, zones: dict[str, Zone]) -> None:
    """Seed zone thresholds."""
    print("Seeding zone thresholds...")
    thresholds_repo = ZoneThresholdsRepositoryImpl(session)

    for zone_id, thresholds in ZONE_THRESHOLDS.items():
        if zone_id in zones:
            await thresholds_repo.upsert(zone_id, thresholds)
            print(f"  Added thresholds for {zone_id}")


async def seed_resource_centers(session: AsyncSession) -> None:
    """Seed realistic resource centers with inventory near Swat district zones."""
    print("Seeding resource centers...")

    center_repo = ResourceCenterRepositoryImpl(session)
    item_repo = InventoryItemRepositoryImpl(session)

    for rc_data in RESOURCE_CENTERS:
        center = ResourceCenter(
            id=rc_data["id"],
            name=rc_data["name"],
            location_zone=rc_data["location_zone"],
        )
        saved_center = await center_repo.add(center)
        print(f"  Added resource center: {saved_center.name}")

        for item_data in rc_data["inventory"]:
            item = InventoryItem(
                id=item_data["id"],
                item_name=item_data["item_name"],
                quantity=item_data["quantity"],
                center_id=saved_center.id,
            )
            await item_repo.add(item)

        print(f"    → {len(rc_data['inventory'])} inventory items")


async def seed_test_user(session: AsyncSession) -> None:
    """Seed the admin user for login."""
    print("Seeding test user...")
    from domain.entities.user import User
    from infrastructure.auth.argon2_hasher import Argon2PasswordHasher
    from infrastructure.db.models import DBUserRole, UserModel
    from sqlalchemy import insert, select

    hasher = Argon2PasswordHasher()

    # Check if user already exists (idempotent)
    result = await session.execute(
        select(UserModel).where(UserModel.username == "admin")
    )
    if result.scalar_one_or_none():
        print("  Admin user already exists — skipping")
        return

    password_hash = hasher.hash("admin123")

    stmt = insert(UserModel).values(
        id="user-admin-001",
        username="admin",
        password_hash=password_hash,
        role=DBUserRole("admin"),
        created_at=datetime.now(UTC),
    )
    await session.execute(stmt)
    print("  Added admin user: admin / admin123")


async def generate_sensor_readings(
    session: AsyncSession,
    zones: dict[str, Zone],
    base_time: datetime,
) -> None:
    """Generate realistic sensor readings for each zone."""
    print("Generating sensor readings...")
    sensor_repo = SensorReadingRepositoryImpl(session)

    # Base water levels that will produce different risk tiers
    base_water_levels = {
        "zone-kalam":   0.8,   # LOW  – well below warning
        "zone-bahrain": 1.2,   # MEDIUM – approaching warning
        "zone-madyan":  2.0,   # HIGH   – at warning threshold
        "zone-mingora": 3.2,   # DANGER – above critical
    }

    for zone_id, zone in zones.items():
        base_level = base_water_levels.get(zone_id, 1.0)

        for i in range(10):
            hours_ago = 24 - (i * 2.5)
            recorded_at = base_time - timedelta(hours=hours_ago)
            variation = random.uniform(-0.1, 0.1)

            reading = SensorReading(
                id=f"sensor-{zone_id}-{i}",
                zone_id=zone_id,
                water_level=WaterLevel(base_level + variation),
                timestamp=recorded_at,
                source="real" if i % 2 == 0 else "test",
            )
            await sensor_repo.add(reading)

        print(f"  Generated readings for {zone.name}")


async def generate_weather_snapshots(
    session: AsyncSession,
    zones: dict[str, Zone],
    base_time: datetime,
) -> dict[str, float]:
    """Generate weather snapshots over 24h and return rainfall amounts by zone."""
    print("Generating weather snapshots...")
    weather_repo = WeatherSnapshotRepositoryImpl(session)

    rainfall_by_zone = {
        "zone-kalam":   65.0,
        "zone-bahrain": 30.0,
        "zone-madyan":  15.0,
        "zone-mingora":  5.0,
    }

    for zone_id, zone in zones.items():
        peak_rainfall = rainfall_by_zone.get(zone_id, 10.0)
        from domain.value_objects.rainfall_window import RainfallWindow

        for i in range(10):
            hours_ago = 24 - (i * 2.5)
            step_time = base_time - timedelta(hours=hours_ago)
            rain_factor = 0.2 + 0.8 * max(0.0, 1.0 - abs(i - 6) / 5.0)
            step_rainfall = round(peak_rainfall * max(0.1, rain_factor), 1)

            snapshot = WeatherSnapshot(
                zone_id=zone_id,
                rainfall=RainfallWindow(millimetres=step_rainfall, duration_hours=24.0),
                fetched_at=step_time,
                ttl_seconds=3600,
            )
            await weather_repo.add(snapshot)

        print(f"  Generated weather time-series for {zone.name}: peak {peak_rainfall}mm")

    return rainfall_by_zone


async def generate_risk_assessments(
    session: AsyncSession,
    zones: dict[str, Zone],
    rainfall_by_zone: dict[str, float],
    base_time: datetime,
) -> dict[str, RiskAssessment]:
    """Generate time-series risk assessments over 24 hours using actual RiskEngine."""
    print("Generating risk assessments using RiskEngine...")
    risk_repo = RiskAssessmentRepositoryImpl(session)
    thresholds_repo = ZoneThresholdsRepositoryImpl(session)
    sensor_repo = SensorReadingRepositoryImpl(session)
    weather_repo = WeatherSnapshotRepositoryImpl(session)

    assessments = {}

    for zone_id, zone in zones.items():
        thresholds = await thresholds_repo.get_by_zone_id(zone_id)
        if not thresholds:
            thresholds = ZONE_THRESHOLDS[zone_id]

        readings = await sensor_repo.list_for_zone(zone_id, limit=10)
        readings = sorted(readings, key=lambda r: r.timestamp)
        weather_snaps = await weather_repo.list_for_zone_in_window(
            zone_id, start_time=base_time - timedelta(hours=25)
        )
        weather_snaps = sorted(weather_snaps, key=lambda w: w.fetched_at)

        risk_engine = RiskEngine()

        for idx, reading in enumerate(readings):
            step_weather = weather_snaps[idx] if idx < len(weather_snaps) else weather_snaps[-1]
            assessment = risk_engine.assess(
                zone=zone,
                current_water_level=reading.water_level,
                forecast_rain_24h=step_weather.rainfall,
                thresholds=thresholds,
                now=reading.timestamp,
            )
            saved = await risk_repo.add(assessment)
            if idx == len(readings) - 1:
                assessments[zone_id] = saved

        latest = assessments[zone_id]
        print(f"  {zone.name}: {latest.tier.name} ({latest.probability:.1%}) with {len(readings)} trend points")

    return assessments


async def apply_escalation(
    session: AsyncSession,
    zones: dict[str, Zone],
    assessments: dict[str, RiskAssessment],
    base_time: datetime,
) -> dict[str, RiskAssessment]:
    """Apply escalation using actual EscalationEngine."""
    print("Applying escalation using EscalationEngine...")
    risk_repo = RiskAssessmentRepositoryImpl(session)

    escalation_engine = EscalationEngine()
    escalation_engine.build_graph(list(zones.values()))
    escalated_assessments = escalation_engine.propagate(assessments)

    final_assessments = {}
    for zone_id, zone in zones.items():
        initial = assessments[zone_id]
        escalated = escalated_assessments[zone_id]

        if escalated != initial:
            saved = await risk_repo.add(escalated)
            final_assessments[zone_id] = saved
            print(f"  {zone.name} escalated {initial.tier.name} → {escalated.tier.name}")
        else:
            final_assessments[zone_id] = initial

    return final_assessments


async def generate_alerts(
    session: AsyncSession,
    zones: dict[str, Zone],
    assessments: dict[str, RiskAssessment],
    base_time: datetime,
) -> None:
    """Generate alerts from risk assessments."""
    print("Generating alerts...")
    alert_repo = AlertRepositoryImpl(session)

    certainty_urgency_combos = [
        ("Observed", "Immediate"),
        ("Likely",   "Expected"),
        ("Possible", "Future"),
    ]

    for zone_id, zone in zones.items():
        assessment = assessments[zone_id]
        if assessment.tier.value < RiskTier.MEDIUM.value:
            continue

        if assessment.tier == RiskTier.DANGER:
            certainty, urgency = certainty_urgency_combos[0]
        elif assessment.tier == RiskTier.HIGH:
            certainty, urgency = certainty_urgency_combos[1]
        else:
            certainty, urgency = certainty_urgency_combos[2]

        alert = Alert(
            zone_id=zone_id,
            severity=assessment.tier,
            certainty=certainty,
            urgency=urgency,
            headline=f"{assessment.tier.name} risk alert for {zone.name}",
            description=assessment.explanation,
            sent_at=base_time + timedelta(minutes=10),
        )
        await alert_repo.add(alert)
        print(f"  Generated {assessment.tier.name} alert for {zone.name}")

    await session.commit()


async def main() -> None:
    """Main seeding function."""
    print("=" * 60)
    print("Seeding demo data for MVP demo")
    print("=" * 60)

    base_time = datetime.now(UTC)

    async with get_session() as session:
        try:
            await clear_existing_data(session)
            zones = await seed_zones(session)
            await seed_zone_thresholds(session, zones)
            await seed_test_user(session)
            await seed_resource_centers(session)
            await generate_sensor_readings(session, zones, base_time)
            rainfall_by_zone = await generate_weather_snapshots(session, zones, base_time)
            assessments = await generate_risk_assessments(session, zones, rainfall_by_zone, base_time)
            final_assessments = await apply_escalation(session, zones, assessments, base_time)
            await generate_alerts(session, zones, final_assessments, base_time)

            print("\n" + "=" * 60)
            print("Demo data seeding complete!")
            print("=" * 60)
            print("\nRisk distribution (after escalation):")
            for zone_id, zone in zones.items():
                assessment = final_assessments[zone_id]
                upstream = " (headwater)" if not zone.upstream_zone_id else f" (downstream of {zone.upstream_zone_id})"
                print(f"  • {zone.name}{upstream}: {assessment.tier.name}")

            print("\nKey demo: Kalam heavy rain → escalation chain → Mingora DANGER")

        except Exception as e:
            await session.rollback()
            print(f"\nError during seeding: {e}")
            import traceback
            traceback.print_exc()
            raise


if __name__ == "__main__":
    asyncio.run(main())
